class_weights: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYDQAAADIyNTQ3MTkzMTQ5NDRxAlgDAAAAY3B1cQNLBk50cQRRLoACXXEAWA0AAAAyMjU0
    NzE5MzE0OTQ0cQFhLgYAAAAAAAAA7JySP3Cvhz8+wy4/BHNtP2skiz+2mrE/
- 0
- !!python/tuple
  - 6
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
learning_rate: 0.003
num_classes: 6
